### PR TITLE
Let defaultRoot be null

### PR DESCRIPTION
**Pull request by P0lip**
Related: #25

### CODE REVIEW

**Review by wmhilton — CHANGES_REQUESTED** [review]
You broke one of the browser tests. (see CI) I can reproduce locally as well.

**Comment by P0lip** [comment]
@wmhilton yeah, these pass on master too
https://app.circleci.com/pipelines/github/stoplightio/json-schema-ref-parser/105/workflows/f0892d4c-d5fa-4bda-a697-ec9593614282/jobs/352
IIRC it's due to screwed mocking.

**Review by wmhilton — APPROVED** [review]
Ha, well in that case...

**Comment by wmhilton** [comment]
@P0lip is this a blocker for anything?

**Pull request merged**
