### PR TITLE
Suggest name version

### PR DESCRIPTION
**Pull request by P0lip**
See https://github.com/stoplightio/platform-internal/pull/4755#pullrequestreview-536914475
Marc, you can yalc it and try out in the platform-internal PR that you reviewed.

### CODE REVIEW

**Review by marbemac — CHANGES_REQUESTED** [review]
See https://github.com/stoplightio/platform-internal/pull/4755#issuecomment-733885286

**Review by marbemac — APPROVED** [review]
Looks good! Could you just ensure that tests and linting etc pass before merging? PR checks are not running on this PR right now.

**Comment by P0lip** [comment]
I'll replace nock with fetch-mock once I'm at it since tests for this new bundling does not run under browser.
Everything else is okay, tho.

**Comment by P0lip** [comment]
Ah dang, I forgot we don't use isomorphic-fetch, but plain `http` :/

**Pull request merged**
